name: central_controller
channels:
  - conda-forge
dependencies:
  - conda-forge::cmake=3.27.4
  - conda-forge::git
  - conda-forge::cxx-compiler
  - conda-forge::c-compiler
  - conda-forge::make
  - conda-forge::pkg-config
  - conda-forge::libpqxx=7.10.1
  - conda-forge::libopentelemetry-cpp=1.21.0
  - conda-forge::libopentelemetry-cpp-headers=1.21.0
  - conda-forge::google-cloud-cpp=2.38.0
  - conda-forge::libgoogle-cloud=2.38.0
  - conda-forge::rust=1.89.0
  - conda-forge::inja=3.3.0
  - conda-forge::libhiredis=1.3.0
  - conda-forge::nlohmann_json=3.12.0
  - conda-forge::jemalloc=5.3.0
  - conda-forge::postgresql=17.6
