# on:
#     workflow_dispatch:
on:
  push:
  workflow_dispatch:

jobs:
  central_controller:
    name: Central Controller Build
    strategy:
      matrix:
        runner: [gha-runner-x64, gha-runner-arm64]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: latest
        activate-environment: central_controller
    - name: Conda Environment Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: ${{ runner.os }}-${{ runner.arch }}-conda-${{ hashFiles('environment.yml') }}
    - name: Update Conda Environment
      run:
        source ~/miniconda3/etc/profile.d/conda.sh
        conda env update --file environment.yml
    - name: Build
      run: |
        source ~/miniconda3/etc/profile.d/conda.sh
        conda activate central_controller
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DZT1_CENTRAL_CONTROLLER=1
        cmake --build build/ --target all -j4 --verbose
    - name: SelfTest
      run: |
        ./build/zerotier-selftest